server:
  port: 8888
#endpoints:
  #shutdown:
     #enabled: true

#application:
 # hello: Hello Angel From application dfdfdaa
#management: 
 # security: 
  # enabled: false
# database name
spring:
  datasource: 
      url : jdbc:mysql://localhost:3306/springboot_db
      username : root
      password : 123
      driverClassName : com.mysql.jdbc.Driver
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  