server:
  port: 8888
#endpoints:
  #shutdown:
     #enabled: true

#application:
 # hello: Hello Angel From application dfdfdaa
management: 
  security: 
   enabled: false
# database name
spring:
  datasource: 
      url : jdbc:mysql://localhost:3306/test
      username : root
      password : 123
      driverClassName : com.mysql.jdbc.Driver
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  redis:
     database: 0
     host: 127.0.0.1  
     password: 
     port: 6379
     pool: 
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  jpa:
     database: MYSQL
     show-sql: true
     hibernate:
        ddl-auto: update
        naming-strategy:  org.hibernate.cfg.ImprovedNamingStrategy
     properties: 
          hibernate:
              dialect:  org.hibernate.dialect.MySQL5Dialect
  